name: "Unreleased Changelog Release"
description: "Create new release out of an unreleased section in changelog file"
branding:
  icon: "file-text"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
